import { cn } from "@/lib/tailwind"
import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import { CSSProperties } from "react"
// import "./globals.css"

const fontSans = FontSans({
  subsets: ["latin"],
  preload: true,
  display: "swap",
  // variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Taurus App",
  description: "Generated by taurus next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={
          {
            WebkitFontSmoothing: "antialiased",
            MozOsxFontSmoothing: "grayscale",
          } as CSSProperties
        }
        className={cn(fontSans.className)}
      >
        {children}
      </body>
    </html>
  )
}
